//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// dxGameTool.rc에서 사용되고 있습니다.
//
#define IDC_LMS_OK                      1
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_dxGameToolTYPE              130
#define ID_WINDOW_MANAGER               131
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define IDS_EDIT_MENU                   306
#define IDD_DLG_MODEL                   320
#define IDR_MODELDLG_MODELLIST_POPUP    322
#define IDD_DLG_RENDER_STATE            325
#define IDD_DIALOG1                     327
#define IDD_DLG_TEXTURE                 327
#define IDR_MENU1                       329
#define IDR_TEXDLG_TEXLIST_POPUP        329
#define IDD_DIALOG2                     330
#define IDD_DLG_LOADMODEL_STATE         330
#define IDC_MODELDLG_MODEL_LISTCTRL     1004
#define IDC_BUTTON1                     1006
#define IDC_MODELDLG_POSX_UPBTN         1006
#define IDC_BUTTON2                     1007
#define IDC_MODELDLG_POSX_DOWNBTN       1007
#define IDC_MODELDLG_ANIPLAY_BTN        1007
#define IDC_EDIT1                       1008
#define IDC_MODELDLG_POSX_EDIT          1008
#define IDC_TEXDLG_PATH_EDIT            1008
#define IDC_BUTTON3                     1009
#define IDC_MODELDLG_POSY_UPBTN         1009
#define IDC_MODELDLG_ANIPAUSE_BTN       1009
#define IDC_BUTTON4                     1010
#define IDC_MODELDLG_POSY_DOWNBTN       1010
#define IDC_MODELDLG_ANIPAUSE_BTN2      1010
#define IDC_MODELDLG_ANISTOP_BTN        1010
#define IDC_EDIT2                       1011
#define IDC_MODELDLG_POSY_EDIT          1011
#define IDC_BUTTON5                     1012
#define IDC_MODELDLG_POSZ_UPBTN         1012
#define IDC_EDIT13                      1012
#define IDC_BUTTON6                     1013
#define IDC_MODELDLG_POSZ_DOWNBTN       1013
#define IDC_EDIT14                      1013
#define IDC_EDIT3                       1014
#define IDC_MODELDLG_POSZ_EDIT          1014
#define IDC_EDIT15                      1014
#define IDC_BUTTON7                     1015
#define IDC_MODELDLG_ROTX_UPBTN         1015
#define IDC_EDIT16                      1015
#define IDC_BUTTON8                     1016
#define IDC_MODELDLG_ROTX_DOWNBTN       1016
#define IDC_EDIT4                       1017
#define IDC_MODELDLG_ROTX_EDIT          1017
#define IDC_BUTTON9                     1018
#define IDC_MODELDLG_ROTY_UPBTN         1018
#define IDC_BUTTON10                    1019
#define IDC_MODELDLG_ROTY_DOWNBTN       1019
#define IDC_EDIT5                       1020
#define IDC_MODELDLG_ROTY_EDIT          1020
#define IDC_BUTTON11                    1021
#define IDC_MODELDLG_ROTZ_UPBTN         1021
#define IDC_BUTTON12                    1022
#define IDC_MODELDLG_ROTZ_DOWNBTN       1022
#define IDC_EDIT6                       1023
#define IDC_MODELDLG_ROTZ_EDIT          1023
#define IDC_BUTTON13                    1024
#define IDC_MODELDLG_SIZEX_UPBTN        1024
#define IDC_BUTTON14                    1025
#define IDC_MODELDLG_SIZEX_DOWNBTN      1025
#define IDC_EDIT7                       1026
#define IDC_MODELDLG_SIZEX_EDIT         1026
#define IDC_BUTTON15                    1027
#define IDC_MODELDLG_SIZEY_UPBTN        1027
#define IDC_BUTTON16                    1028
#define IDC_MODELDLG_SIZEY_DOWNBTN      1028
#define IDC_EDIT8                       1029
#define IDC_MODELDLG_SIZEY_EDIT         1029
#define IDC_BUTTON17                    1030
#define IDC_MODELDLG_SIZEZ_UPBTN        1030
#define IDC_BUTTON18                    1031
#define IDC_MODELDLG_SIZEZ_DOWNBTN      1031
#define IDC_EDIT9                       1032
#define IDC_MODELDLG_SIZEZ_EDIT         1032
#define IDC_BUTTON19                    1033
#define IDC_MODELDLG_VELX_UPBTN         1033
#define IDC_BUTTON20                    1034
#define IDC_MODELDLG_VELX_DOWNBTN       1034
#define IDC_EDIT10                      1035
#define IDC_MODELDLG_VELX_EDIT          1035
#define IDC_BUTTON21                    1036
#define IDC_MODELDLG_VELY_UPBTN         1036
#define IDC_BUTTON22                    1037
#define IDC_MODELDLG_VELY_DOWNBTN       1037
#define IDC_EDIT11                      1038
#define IDC_MODELDLG_VELY_EDIT          1038
#define IDC_BUTTON23                    1039
#define IDC_MODELDLG_VELZ_UPBTN         1039
#define IDC_BUTTON24                    1040
#define IDC_MODELDLG_VELZ_DOWNBTN       1040
#define IDC_EDIT12                      1041
#define IDC_MODELDLG_VELZ_EDIT          1041
#define IDC_TREE2                       1042
#define IDC_MODELDLG_OBJECT_TREE        1042
#define IDC_MODELDLG_POSY_SPIN          1048
#define IDC_RENDERDLG_BACKFACE_NONE_RADIO 1048
#define IDC_RENDERDLG_CULLMODE_NONE_RADIO 1048
#define IDC_MODELDLG_POSZ_SPIN          1049
#define IDC_RENDERDLG_BACKFACE_CW_RADIO 1049
#define IDC_RENDERDLG_CULLMODE_FRONTFACE_RADIO 1049
#define IDC_MODELDLG_POSX_SPIN          1050
#define IDC_RENDERDLG_BACKFACE_CCW_RADIO 1050
#define IDC_RENDERDLG_CULLMODE_BACKFACE_RADIO 1050
#define IDC_MODELDLG_ROTX_SPIN          1051
#define IDC_MODELDLG_ROTY_SPIN          1052
#define IDC_MODELDLG_ROTZ_SPIN          1053
#define IDC_RENDERDLG_RENDERMODE_FILL_RADIO 1053
#define IDC_RENDERDLG_RENDERMODE_SOLID_RADIO 1053
#define IDC_MODELDLG_SIZEZ_SPIN         1054
#define IDC_RADIO5                      1054
#define IDC_RENDERDLG_RENDERMODE_WIREFRAME_RADIO 1054
#define IDC_MODELDLG_SIZEY_SPIN         1055
#define IDC_MODELDLG_SIZEX_SPIN         1056
#define IDC_MODELDLG_VELX_SPIN          1057
#define IDC_MODELDLG_VELY_SPIN          1058
#define IDC_MODELDLG_VELZ_SPIN          1059
#define IDC_CHECK2                      1061
#define IDC_MODELDLG_MODEL_NORMALIZE_CHECK 1061
#define IDC_LMS_FLIPUV_CHECK            1061
#define IDC_LIST3                       1063
#define IDC_TEXDLG_TEXTURE_LISTCTRL     1063
#define IDC_TREE1                       1065
#define IDC_TEXDLG_TREE_OBJLIST         1065
#define IDC_TEXDLG_TREE_OBJLIST2        1066
#define IDC_COMBO1                      1067
#define IDC_TEXDLG_COMBO_DIFFUSE        1067
#define IDC_COMBO2                      1068
#define IDC_TEXDLG_COMBO_ALPHA          1068
#define IDC_COMBO3                      1069
#define IDC_TEXDLG_COMBO_BUMP           1069
#define IDC_COMBO4                      1070
#define IDC_TEXDLG_COMBO_SPECULAR       1070
#define IDC_COMBO5                      1071
#define IDC_TEXDLG_COMBO_LIGHT          1071
#define IDC_TEXDLG_COMBO_MODELLIST      1072
#define IDC_CHECK1                      1073
#define IDC_LMS_HIERARCHY_CHECK         1073
#define IDC_MODELDLG_MODEL_ANIREPEAT_CHECK 1073
#define IDC_CHECK3                      1074
#define IDC_LMS_FLIPWIND_CHECK          1074
#define IDC_CHECK4                      1075
#define IDC_LMS_LEFTHAND_CHECK          1075
#define IDC_CHECK5                      1076
#define IDC_LMS_GENNORMAL_CHECK         1076
#define IDC_LMS_IDOK                    1077
#define IDC_SPIN1                       1080
#define IDC_MODELDLG_ANI_LISTCTRL       1090
#define IDC_TEX_IMGFRAME_GROUP          1091
#define ID_INSERT_INSERTMODEL           32771
#define ID_DELETE_DELETEMODEL           32772
#define ID_INSERT_INSERTMODEL32773      32773
#define ID_INSERTMODEL_GEOMETRYTRIANGLE 32774
#define ID_INSERTMODEL_GEOMETRYCUBE     32775
#define ID_INSERTMODEL_GEOMETRYSPHERE   32776
#define ID_INSERT_INSERTMODEL32777      32777
#define ID__LOAD_MODEL                  32778
#define ID_DELETE_DELETE                32779
#define ID_INSERT_INSERTTEXTURE         32780
#define ID_DELETE_DELETETEXTURE         32781
#define ID_INSERT_DELETEMODEL           32782
#define ID_MODELDATA_DELETE             32783
#define ID_LOAD_MODEL                   32784
#define ID_DELETE_MODEL                 32785
#define ID_INSERT_DELETETEXTURE         32786
#define ID_INSERT_TEXTURE               32787
#define ID_DELETE_TEXTURE               32788
#define ID_ANIMATIONDATA_LOADANIMATION  32789
#define ID_ANIMATIONDATA_DELETEANIMATION 32790
#define ID_LOAD_ANIMATION               32791
#define ID_DELETE_ANIMATION             32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        337
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
